export const HOME_USERNAME_CHANGED = 'HOME_USERNAME_CHANGED'
export const HOME_PASSWORD_CHANGED = 'HOME_PASSWORD_CHANGED'
export const HOME_SIGN_IN = 'HOME_SIGN_IN'
export const HOME_SIGN_OUT = 'HOME_SIGN_OUT'
export const HOME_REMEMBER_ME_CHANGED = 'HOME_REMEMBER_ME_CHANGED'
export const HOME_PASSWORD_RECOVERY_NEEDED = 'HOME_PASSWORD_RECOVERY_NEEDED'
export const HOME_PASSWORD_RECOVERY_SENT = 'HOME_PASSWORD_RECOVERY_SENT'

export const APPLICATION_GET_USER_PROPERTIES = 'APPLICATION_GET_USER_PROPERTIES'

export const MAP_USER_POSITION_CHANGE_STARTED = 'MAP_USER_POSITION_CHANGE_STARTED'
export const MAP_USER_POSITION_CHANGE_FINISHED = 'MAP_USER_POSITION_CHANGE_FINISHED'
export const MAP_USER_POSITION_CHANGE_ERROR = 'MAP_USER_POSITION_CHANGE_ERROR'

export const MAP_VIEWPORT_CHANGED = 'MAP_VIEWPORT_CHANGED'
